
hume:
  key-prefix: "hume_"
  redis:
    host: 127.0.0.1
    password: nice:redis
    port: 6379
    lettuce:
      pool:
        max-active: 5
spring:
  redis:
    port: 6379
    host: 127.0.0.1
    password: nice:redis
    database: 1
    lettuce:
      pool:
        min-idle: 2
        max-active: 8
        max-idle: 8
        max-wait: 10000

